### ISSUE TITLE
undeclared signals in design

### ISSUE THREAD

**Issue by ghost** [verilog-to-routing/vtr-verilog-to-routing#229] opened 2017-08-13 17:33 UTC
When synthesizing a circuit with ODIN, if there are signals in the design that are not declared, a segmentation fault occurs which is misleading!
it is supposed to report it via an error.

**Comment by jeanlego** [comment] 2018-06-16 20:05
unable to reproduce, works and Odin reports that the signal is undeclared. or if an undeclared signal is used for a module, Odin will create a dummy wire by default and set it to gnd (other tools do this by default too).

closing unless someone has a way to reproduce

**Closed by jeanlego** 2018-06-16 20:05 UTC
Labels: Odin
