### ISSUE TITLE
Odin fails when executing run_vtr_flow.pl 

### ISSUE THREAD

**Issue by a181d129** [verilog-to-routing/vtr-verilog-to-routing#640] opened 2019-06-06 20:26 UTC
I am trying to run run_vtr_flow.pl script.After going to the vtr_flow/tasks directory, I wrote the following command :
../scripts/run_vtr_task.pl basic_flow
It gives me the following message :
k6_frac_N10_mem32K_40nm.xml/ch_intrinsics.v/common 
                           failed: odin
				I am confused about the reason of failure. could someone help me out?
I am running the vtr-verilog-to-routing-master tool from windows machine using WinSCP

**Comment by jeanlego** [comment] 2019-06-08 03:20
this seems related to your setup

could you put the output of the file ? 

> vtr_flow/tasks/basic_flow/run001/k6_frac_N10_mem32K_40nm.xml/ch_intrinsics.v/common/odin.out

**Comment by jeanlego** [comment] 2019-06-22 02:26
Unable to reproduce, closing

**Closed by jeanlego** 2019-06-22 02:26 UTC
