### ISSUE TITLE
Do not support the constant shift

### ISSUE THREAD

**Issue by kmurray** [verilog-to-routing/vtr-verilog-to-routing#38] opened 2015-06-26 15:57 UTC
Originally reported on Google Code with ID 45

```
What steps will reproduce the problem?
1. gdb ./odin_II.exe
2.r -V a25/a25_decode.v
3.

What is the expected output? What do you see instead?
When using the right shift operator, it should work. but it doesn't support it with
localparam or arrays.

error:(Line number: 1430) Odin only supports constant shifts at present

Line: 1239(a25_decode.v  (1'd1 << instruction[19:16]))

What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Reported by `JanetChina.V` on 2012-10-25 19:03:39

<hr>
- _Attachment: [a25_decode.v](https://storage.googleapis.com/google-code-attachments/vtr-verilog-to-routing/issue-45/comment-0/a25_decode.v)_
- _Attachment: [a25_decompile.v](https://storage.googleapis.com/google-code-attachments/vtr-verilog-to-routing/issue-45/comment-0/a25_decompile.v)_
- _Attachment: [debug_functions.v](https://storage.googleapis.com/google-code-attachments/vtr-verilog-to-routing/issue-45/comment-0/debug_functions.v)_

**Comment by vincelasal** [comment] 2015-09-22 19:12
Currently being investigated by Zack.

**Comment by mflawn** [comment] 2019-06-05 20:16
Still outstanding issue, see attached the file to reproduce:

[a25_decode_fix.v.txt](https://github.com/verilog-to-routing/vtr-verilog-to-routing/files/3258879/a25_decode_fix.v.txt)


```
Converting AST into a Netlist. Note this netlist can be viewed using GraphViz (see documentation) 
==========================
Detected Top Level Module:      a25_decode
==========================
-------------- 
Odin has decided you have failed ;)

ERROR (1):NETLIST_ERROR (File: a25/a25_decode_fix.v) (Line number: 1239) Odin only supports constant shifts at present

                                                        (instruction[15:0] & (1'd1 << instruction[19:16]));
ASSERT FAILED:
        @[/mnt/c/Users/casa/vtr-verilog-to-routing/ODIN_II/SRC/netlist_create_from_ast.cpp]create_operation_node::4213  
Aborted (core dumped)
```

**Comment by jeanlego** [comment] 2020-09-24 18:00
closing since #1560 add variable shift support

**Closed by jeanlego** 2020-09-24 18:00 UTC
Labels: Good First Issue, Odin, Odin Elaboration, Odin Tech.Mapping, bug, enhancement, lang-hdl
