### ISSUE TITLE
Unitialized Variables in rr_graph_uxsdcxx_serializer.h

### ISSUE THREAD

**Issue by kmurray** [verilog-to-routing/vtr-verilog-to-routing#1114] opened 2020-02-06 15:12 UTC
#### Expected Behaviour

VPR should build without warnings

#### Current Behaviour

With gcc-7:
```
n file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h: In function ‘void uxsd::load_channels(const pugi::xml_node&, T&, Context&, const std::function<void(const char*)>*, ptrdiff_t*) [with T = RrGraphSerializer; Context = void*]’:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1030:36: warning: ‘y_list_info’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         chan_width_->y_list[index] = info;
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:2693:21: note: ‘y_list_info’ was declared here
                 int y_list_info;
                     ^~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1026:25: warning: ‘y_list_index’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             report_error(
             ~~~~~~~~~~~~^
                 "index %d on y_list exceeds y_list size %u",
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 index, chan_width_->y_list.size());
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:2692:30: note: ‘y_list_index’ was declared here
                 unsigned int y_list_index;
                              ^~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1003:36: warning: ‘x_list_info’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         chan_width_->x_list[index] = info;
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:2685:21: note: ‘x_list_info’ was declared here
                 int x_list_info;
                     ^~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:999:25: warning: ‘x_list_index’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             report_error(
             ~~~~~~~~~~~~^
                 "index %d on x_list exceeds x_list size %u",
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 index, chan_width_->x_list.size());
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:2684:30: note: ‘x_list_index’ was declared here
                 unsigned int x_list_index;
                              ^~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h: In function ‘void uxsd::load_block_types(const pugi::xml_node&, T&, Context&, const std::function<void(const char*)>*, ptrdiff_t*) [with T = RrGraphSerializer; Context = void*]’:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1161:41: warning: ‘pin_ptc’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (block_type_pin_index_to_name(tile, ptc) != value) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3070:21: note: ‘pin_ptc’ was declared here
                 int pin_ptc;
                     ^~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1830:9: warning: ‘pin_class_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         switch (type) {
         ^~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3149:31: note: ‘pin_class_type’ was declared here
                 enum_pin_type pin_class_type;
                               ^~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1297:9: warning: ‘block_type_width’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (block_info.width != width) {
         ^~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3214:21: note: ‘block_type_width’ was declared here
                 int block_type_width;
                     ^~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1296:60: warning: ‘block_type_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         const auto& block_info = physical_tile_types_.at(id);
                                                            ^
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3213:21: note: ‘block_type_id’ was declared here
                 int block_type_id;
                     ^~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1301:9: warning: ‘block_type_height’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (block_info.height != height) {
         ^~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3212:21: note: ‘block_type_height’ was declared here
                 int block_type_height;
                     ^~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h: In function ‘void uxsd::load_switch(const pugi::xml_node&, T&, Context&, const std::function<void(const char*)>*, ptrdiff_t*) [with T = RrGraphSerializer; Context = t_rr_switch_inf*]’:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:433:28: warning: ‘sizing_mux_trans_size’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         sw->mux_trans_size = mux_trans_size;
         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:2797:23: note: ‘sizing_mux_trans_size’ was declared here
                 float sizing_mux_trans_size;
                       ^~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:432:22: warning: ‘sizing_buf_size’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         sw->buf_size = buf_size;
         ~~~~~~~~~~~~~^~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:2796:23: note: ‘sizing_buf_size’ was declared here
                 float sizing_buf_size;
                       ^~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h: In function ‘void uxsd::load_rr_edges(const pugi::xml_node&, T&, Context&, const std::function<void(const char*)>*, ptrdiff_t*) [with T = RrGraphSerializer; Context = void*]’:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:818:33: warning: ‘edge_switch_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             bind.set_edge_target(src_node, sink_node, switch_id);
             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3683:30: note: ‘edge_switch_id’ was declared here
                 unsigned int edge_switch_id;
                              ^~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:811:25: warning: ‘edge_src_node’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             report_error(
             ~~~~~~~~~~~~^
                 "source_node %d is larger than rr_nodes.size() %d",
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 src_node, rr_nodes_->size());
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3682:30: note: ‘edge_src_node’ was declared here
                 unsigned int edge_src_node;
                              ^~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:818:33: warning: ‘edge_sink_node’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             bind.set_edge_target(src_node, sink_node, switch_id);
             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3681:30: note: ‘edge_sink_node’ was declared here
                 unsigned int edge_sink_node;
                              ^~~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h: In function ‘void uxsd::load_node(const pugi::xml_node&, T&, Context&, const std::function<void(const char*)>*, ptrdiff_t*) [with T = RrGraphSerializer; Context = int]’:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3518:22: warning: ‘node_segment_segment_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.init_node_segment(context, node_segment_segment_id);
                      ^~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:618:49: warning: ‘node_timing_R’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         node.set_rc_index(find_create_rr_rc_data(R, C));
                           ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3509:23: note: ‘node_timing_R’ was declared here
                 float node_timing_R;
                       ^~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:618:49: warning: ‘node_timing_C’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         node.set_rc_index(find_create_rr_rc_data(R, C));
                           ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3508:23: note: ‘node_timing_C’ was declared here
                 float node_timing_C;
                       ^~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:563:29: warning: ‘node_loc_ylow’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         node.set_coordinates(xlow, ylow, xhigh, yhigh);
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3501:21: note: ‘node_loc_ylow’ was declared here
                 int node_loc_ylow;
                     ^~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:563:29: warning: ‘node_loc_yhigh’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         node.set_coordinates(xlow, ylow, xhigh, yhigh);
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3500:21: note: ‘node_loc_yhigh’ was declared here
                 int node_loc_yhigh;
                     ^~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:563:29: warning: ‘node_loc_xlow’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         node.set_coordinates(xlow, ylow, xhigh, yhigh);
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3499:21: note: ‘node_loc_xlow’ was declared here
                 int node_loc_xlow;
                     ^~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:563:29: warning: ‘node_loc_xhigh’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         node.set_coordinates(xlow, ylow, xhigh, yhigh);
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3498:21: note: ‘node_loc_xhigh’ was declared here
                 int node_loc_xhigh;
                     ^~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:564:25: warning: ‘node_loc_ptc’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         node.set_ptc_num(ptc);
         ~~~~~~~~~~~~~~~~^~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3497:21: note: ‘node_loc_ptc’ was declared here
                 int node_loc_ptc;
                     ^~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h: In function ‘void uxsd::load_rr_graph(const pugi::xml_node&, T&, Context&, const std::function<void(const char*)>*, ptrdiff_t*) [with T = RrGraphSerializer; Context = void*]’:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3589:22: warning: ‘node_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.add_rr_nodes_node(context, node_capacity, node_id, node_type);
                      ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3587:32: note: ‘node_type’ was declared here
                 enum_node_type node_type;
                                ^~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3589:22: warning: ‘node_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.add_rr_nodes_node(context, node_capacity, node_id, node_type);
                      ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3586:30: note: ‘node_id’ was declared here
                 unsigned int node_id;
                              ^~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3589:22: warning: ‘node_capacity’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.add_rr_nodes_node(context, node_capacity, node_id, node_type);
                      ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3585:30: note: ‘node_capacity’ was declared here
                 unsigned int node_capacity;
                              ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3296:22: warning: ‘grid_loc_y’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.add_grid_locs_grid_loc(context, grid_loc_block_type_id, grid_loc_height_offset, grid_loc_width_offset, grid_loc_x, grid_loc_y);
                      ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3294:21: note: ‘grid_loc_y’ was declared here
                 int grid_loc_y;
                     ^~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3296:22: warning: ‘grid_loc_x’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.add_grid_locs_grid_loc(context, grid_loc_block_type_id, grid_loc_height_offset, grid_loc_width_offset, grid_loc_x, grid_loc_y);
                      ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3293:21: note: ‘grid_loc_x’ was declared here
                 int grid_loc_x;
                     ^~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3296:22: warning: ‘grid_loc_width_offset’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.add_grid_locs_grid_loc(context, grid_loc_block_type_id, grid_loc_height_offset, grid_loc_width_offset, grid_loc_x, grid_loc_y);
                      ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3292:21: note: ‘grid_loc_width_offset’ was declared here
                 int grid_loc_width_offset;
                     ^~~~~~~~~~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3296:22: warning: ‘grid_loc_height_offset’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.add_grid_locs_grid_loc(context, grid_loc_block_type_id, grid_loc_height_offset, grid_loc_width_offset, grid_loc_x, grid_loc_y);
                      ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3291:21: note: ‘grid_loc_height_offset’ was declared here
                 int grid_loc_height_offset;
                     ^~~~~~~~~~~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3296:22: warning: ‘grid_loc_block_type_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 auto child_context = out.add_grid_locs_grid_loc(context, grid_loc_block_type_id, grid_loc_height_offset, grid_loc_width_offset, grid_loc_x, grid_loc_y);
                      ^~~~~~~~~~~~~
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:3290:21: note: ‘grid_loc_block_type_id’ was declared here
                 int grid_loc_block_type_id;
                     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:1131:35: warning: ‘segment_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         return &segment_inf_.at(id);
                                   ^
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:2996:21: note: ‘segment_id’ was declared here
                 int segment_id;
                     ^~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:18:0:
/project/trees/vtr/vpr/src/route/rr_graph_uxsdcxx_serializer.h:464:28: warning: ‘switch_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         make_room_in_vector(rr_switch_inf_, id);
         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from /project/trees/vtr/vpr/src/route/rr_graph_reader.cpp:19:0:
/project/trees/vtr/vpr/src/route/gen/rr_graph_uxsdcxx.h:2861:21: note: ‘switch_id’ was declared here
                 int switch_id;
                     ^~~~~~~~~
```

#### Possible Solution

Since this is in the generated code, it seems like the uxsdcxx generator will need to be updated to ensure these variables are always initialized.

#### Steps to Reproduce

1. Checkout  revision: 868126ec9545344db9b36a02534d7ca7814b1a97 (current master)
2. make vpr

#### Context

VTR should build warning clean, so that any newly introduced warnings are quickly identified and fixed. Keeping even otherwise innocuous warnings around makes it much more difficult for developers to do this.

#### Your Environment

* VTR revision used: 868126ec9545344db9b36a02534d7ca7814b1a97
* Operating System and version: Ubuntu 18.04
* Compiler version: gcc-7

**Comment by kmurray** [comment] 2020-02-06 15:13
@duck2 Any thoughts on this?

**Comment by kmurray** [comment] 2020-02-06 15:34
Interestingly, some further investigation shows that these warnings only show up if built with VTR_ENABLE_IPO_BUILD=off.

Likely when doing IPO/LTO the compiler defers the warnings until the final link stage. But we've suppressed those link-stage warnings for other reasons (#634)

**Comment by litghost** [comment] 2020-02-06 21:06
This is caused by a bug in gcc 7's static analyzer. I've tried added "[[noreturn]]" to attr_error, which would be called if the variable in question was in fact uninitialized.

**Comment by duck2** [comment] 2020-02-06 21:35
I'm seeing the same warnings on g++ 9. Maybe g++ can't follow our (rather convoluted) way of initializing, say, `switch_id`? In the currently generated code, if there is no `id` attribute, the code would throw. And else, if there is an `id` attribute which would cause `strtol` to report an `errno`, the code would again throw. So we know that we have an `int` to assign to `id` if the code didn't throw.

We can just zero-initialize the variables but I don't think this would be helping much in terms of code quality. It's still a solution, though.

**Comment by litghost** [comment] 2020-02-06 21:40
> We can just zero-initialize the variables but I don't think this would be helping much in terms of code quality. It's still a solution, though.

There is actually a runtime cost to zero initialization, so ideally we'd avoid it.

**Comment by litghost** [comment] 2020-02-06 21:40
> I'm seeing the same warnings on g++ 9. Maybe g++ can't follow our (rather convoluted) way of initializing, say, `switch_id`? In the currently generated code, if there is no `id` attribute, the code would throw. And else, if there is an `id` attribute which would cause `strtol` to report an `errno`, the code would again throw. So we know that we have an `int` to assign to `id` if the code didn't throw.

I dramatically simplified the checking (just a bool), and gcc still couldn't figure it out.  GCC is simply broken in this check.

**Comment by kmurray** [comment] 2020-02-06 21:51
> We can just zero-initialize the variables but I don't think this would be helping much in terms of code quality. It's still a solution, though.

I'd suggest giving this a try. It really isn't good to have these warnings (even if they're actually false positives). We can then measure if there is a significant run-time cost.

**Comment by litghost** [comment] 2020-02-06 21:51
As far as I can tell GCC cannot be trusted with detecting uninitialized variables in this case.  Overall my recommendation is to disable this code, link with examples: https://stackoverflow.com/questions/14132898/gcc-wuninitialized-wmaybe-uninitialized-issues 

I can also refactor the code to avoid zero initialization using `std::tuple`.

**Comment by litghost** [comment] 2020-02-06 22:37
> I can also refactor the code to avoid zero initialization using `std::tuple`.

This does not work, the same warning is generated.  Interestingly enough, the simple bool check works with the tuple addition, so the compiler isn't totally broken.  It just is unable to through follow pointers or bitset logic.

**Closed** 2020-02-11 16:47 UTC
Labels: VPR, bug
