### ISSUE TITLE
fix_pins doesn't work with architectures that have different IO types on each edge

### ISSUE THREAD

**Issue by mithro** [verilog-to-routing/vtr-verilog-to-routing#349] opened 2018-05-26 22:42 UTC
We have a different IO type on each of the edges on the device. This works fine until I tried to use `--fix_pins` and you get the following behaviour.

#### Expected Behaviour

Packer sets the correct block_types which match the specification in `--fix_pins` information.

#### Current Behaviour

During packing, each of the signals is assigned a random IO type.

Then during placement you get the following error;
```
Error 1857: Block 10 type (BLK_TL-PIO_R) does not match grid location (1,10) type (BLK_TL-PIO_L).
Error 1858: Block 8 type (BLK_TL-PIO_B) does not match grid location (14,5) type (BLK_TL-PIO_R).
Error 1859: Block 9 type (BLK_TL-PIO_L) does not match grid location (14,7) type (BLK_TL-PIO_R).
Error 1860: Block 6 type (BLK_TL-PIO_T) does not match grid location (14,8) type (BLK_TL-PIO_R).
```

io.place file;
```
#block name     x       y       subblk    pcf    net    Pin   X    Y   subblk  vx  xy
#----------     --      --      ------    ------ ---    ---   --   --  ------  --  --
out:LED2        14      8       1       # set_io LED2   59    13   7   1       14   8
out:LED3        14      7       1       # set_io LED3   56    13   6   1       14   7
out:LED4        14      5       1       # set_io LED4   53    13   4   1       14   5
out:LED5        14      4       1       # set_io LED5   51    13   3   1       14   4
clk             1       10      0       # set_io clk 	13    0    9   0       1   10
```

#### Possible Solution

A solution is for the packer to look up the tile type for each of the signals and pack into that tile type.

My current work around is to use the same IO tile type on all edges.

#### Steps to Reproduce
1. Create an architecture with different IO pin types on each edge.
2. Try to use `--fix_pins`

#### Your Environment
```
VPR FPGA Placement and Routing.
Version: 8.0.0-dev+vpr-7.0.5-5894-g936a52f48-dirty
Revision: vpr-7.0.5-5894-g936a52f48-dirty
Compiled: 2018-05-26T15:17:21 (debug build)
Compiler: GNU 6.3.0 on Linux-4.9.0-4-amd64 x86_64
University of Toronto
vtr-users@googlegroups.com
This is free open source code under MIT license.
```

**Comment by kmurray** [comment] 2018-05-28 15:53
Thanks for the report!

This is a known limitation (duplicate of #268). See #268 for more background.

**Closed by kmurray** 2018-05-28 15:53 UTC
