### ISSUE TITLE
run_vtr_flow.pl -starting_stage ABC

### ISSUE THREAD

**Issue by werneazc** [verilog-to-routing/vtr-verilog-to-routing#144] opened 2016-07-06 13:24 UTC
Hi,

I run a benchmarking with **run_vtr_flow.pl** and started the script at abc. If I do so, the used architecture file is mentioned with the name of the circuit. For parsing I need the name of the architecture in _vpr.out_ or _vpr_stdout.log_.

It would be great if one can fix this naming error.

example:
Architecture file: mycircuit
Circuit name: mycircuit.blif

Best regards
André

**Comment by kmurray** [comment] 2016-07-06 16:01
Hi André,

What is the exact command you are running?

I tried (where `<vtr>` is the root of the VTR source tree):
```
<vtr>/vtr_flow/scripts/run_vtr_flow.pl <vtr>/vtr_flow/benchmarks/blif/6/alu4.blif <vtr>/vtr_flow/arch/timing/k6_frac_N10_40nm.xml -starting_stage abc
```

Which produced:
```
Architecture file: k6_frac_N10_40nm.xml
Circuit name: alu4.blif
```
As expected in both `vpr.out` and `vpr_stdout.log`.

**Comment by werneazc** [comment] 2016-07-06 16:30
Hey, I used the following command:

VTR_ROOT/vtr_flow/scripts/run_vtr_flow.pl mycircuit.blif myarch.xml -starting_stage abc -temp_dir ./myarch

VTR_ROOT is the path to my directory of vtr git repository.
I executed it not in the VTR source tree.

Best regards
André

**Comment by kmurray** [comment] 2016-07-06 17:19
This should now be fixed by 56cdc03dd.

The bug was caused by incorrect handling of relative paths without any `/`s in them.  The updated code should be more robust.

**Closed by kmurray** 2016-07-06 17:19 UTC
